<div class="home">
  <div class="container-center">
    <section class="border-shadow-home">
      <div class="btn tooltip-container">
        <div>
          <a href=" /<?= $scMetaLanguage ?>/Gallery">
            <i class='bx bx-images'></i>
          </a>
          <span class="tooltip-text-left">Gallery</span>
        </div>
        <div>
          <a href="https://maps.app.goo.gl/mqqdiZgfjGW2oy7m7" target="_blank" rel="noopener noreferrer">
            <i class='bx bxs-map'></i>
          </a>
          <span class="tooltip-text-left">Location</span>
        </div>
      </div>
      <div class="address">
        <h2 class="branding-title"><?= $scMetaCopyright ?></h2>
        <h3 class="branding-address-title">Rue du Tier 32,</h3>
        <span class="branding-address">6660 Nadrin - Houffalize</span>
        <span class="branding-address">Luxembourg Belgique</span>
      </div>
      <div class="description">
        <p>
          <?= $trans['home']['description'] ?><br />
          <?= $trans['branding']['slogan'] ?>
        </p>
      </div>
    </section>
  </div>
</div>